FROM python:3.10-alpine

WORKDIR /app

# Install curl for health checks
RUN apk add --no-cache curl

# Copy all files except the Dockerfile itself
COPY . /app/

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose port
EXPOSE 5000

CMD ["gunicorn", "-k", "uvicorn.workers.UvicornWorker", "main:app", "--bind", "0.0.0.0:5000", "--pythonpath", "/app", "--timeout", "0"]